[build]
target = "index.html"
output = "dist"
public_url = "/"

[[hooks]]
stage = "build"
command = "npm"
command_arguments = ["run", "tailwind"]

[[hooks]]
stage = "post_build"
command = "echo"
command_arguments = ["Build complete!"]
